# Generated by Django 5.2.17 on 2026-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_muallif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='muallif',
            field=models.CharField(max_length=100),
        ),
    ]
