# Generated by Django 5.2.17 on 2026-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_muallif'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='postlar/'),
        ),
    ]
